<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <dependencies>
        <!-- Note: this version has a potential vulnerability according to Intellij: CVE-2025-48924
        According to the description, the runner/import that uses this should not be affected.
        -->
        <dependency>
            <groupId>com.opencsv</groupId>
            <artifactId>opencsv</artifactId>
            <version>5.12.0</version>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.ejml/ejml-core -->
        <dependency>
            <groupId>org.ejml</groupId>
            <artifactId>ejml-core</artifactId>
            <version>0.44.0</version>
            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.ejml/ejml-simple -->
        <dependency>
            <groupId>org.ejml</groupId>
            <artifactId>ejml-simple</artifactId>
            <version>0.44.0</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <groupId>com.michaelpascale</groupId>
    <artifactId>neural-networks</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Java Neural Networks</name>

</project>